@echo off
md "App\QQ"
md "App\QQNT"
md "App\TIM"
md "App\WeChat"
md "App\WXWork"
md "App\WeMeet"
md "App\TencentDocs"
md "App\WeiyunApp"
md "Data\Common Files"
md "Data\Common Files (x86)"
md "Data\Documents\Tencent"
md "Data\Documents\WeChat"
md "Data\Documents\WXWork"
md "Data\Roaming\Tencent"
md "Data\Roaming\TencentDocs"
md "Data\Roaming\WeiyunApp"
md "Data\SysWOW64"
md "Data\ProgramData\Tencent"
md "Data\Downloads"
md "Desktop"
md "Scripts"
